<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataMahasiswa = [
            ['nim' => '23190008', 'nama' => 'Alfiah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190009', 'nama' => 'Deawi Guna Pratiwi', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190011', 'nama' => 'Melinda Eviyanti', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190014', 'nama' => 'Fitrohtun Nisha', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190016', 'nama' => 'Heni Melita Ulfianah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190021', 'nama' => 'Adam Yudhistira', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190023', 'nama' => 'Nur Fajri Hidayat', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190024', 'nama' => 'Diajeng Salwa Aulan Ni\'Mah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190026', 'nama' => 'Aulia Annisa', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190027', 'nama' => 'Merlina Eki Widiyasari', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190028', 'nama' => 'Teguh Purwanto', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190029', 'nama' => 'Reny Ristanty', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190035', 'nama' => 'Sahrul Ferdiansah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190039', 'nama' => 'Anisa Fitri', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190043', 'nama' => 'Nabila Nurul Syafa\'At', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190047', 'nama' => 'Rifqi Maulana Mabruri', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190049', 'nama' => 'Rafly Ashraffi Rachmat', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190050', 'nama' => 'Zelda Ammarsa Saefna Putri', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190056', 'nama' => 'Ariyan Andryan Aryja', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190058', 'nama' => 'Rangga Dwi Aditya', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190062', 'nama' => 'Ivan Rifa\'At Arundaya', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190064', 'nama' => 'M. Faiz Mubarok', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190068', 'nama' => 'Adelia Vicka Febrian', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '22180052', 'nama' => 'Misbahudin', 'jurusan' => 'Teknik Informatika', 'semester' => '8', 'alamat' => '-'],
            ['nim' => '23190005', 'nama' => 'M.Hasan Nafi', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190007', 'nama' => 'Moh. Harun Al Rasyid', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190012', 'nama' => 'Nisrina Salwa Muadzah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190017', 'nama' => 'Ratu Vindy Syafira', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190036', 'nama' => 'Ratna Amaliyah Mahmudah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190041', 'nama' => 'Ferdita Lusiana', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190042', 'nama' => 'Rosalia Indah Dwi Putriningsih', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190045', 'nama' => 'Firani Nur Anjani', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190052', 'nama' => 'Najiyatu Khasna Ulfauziyyah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190053', 'nama' => 'Urip Fatahilah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190054', 'nama' => 'Kuinsi Manda Aulia Hutasoit', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190060', 'nama' => 'Muhammad Bahij Aqil Maddani', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190092', 'nama' => 'Faiz Izza Nurhidayatullah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190001', 'nama' => 'Ahmad Khoerul Anam', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190037', 'nama' => 'Zakia Normarissa', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190003', 'nama' => 'Firman Hidayatulloh', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190010', 'nama' => 'Haris Maulana', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190046', 'nama' => 'Mohamad Naufal Kisnoto', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190019', 'nama' => 'Ega Prasetio', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190022', 'nama' => 'Muhamad Yogi Prasetyo', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190031', 'nama' => 'Alisa Fitriani', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190032', 'nama' => 'Sefvia', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190033', 'nama' => 'Ade Lia Farizah', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190063', 'nama' => 'Slamet', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190065', 'nama' => 'Gibran Yudha Iniesta', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23190067', 'nama' => 'Sopiah Apriyani', 'jurusan' => 'Teknik Informatika', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290001', 'nama' => 'Muhammad Ilham Nugroho', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290002', 'nama' => 'Rizky Panca Nugrah', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290003', 'nama' => 'Hanif Abbasy Ahnaf', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290004', 'nama' => 'Fahrur Reza Irawan', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290005', 'nama' => 'Moh Galih Prayoga Eka Putra', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23290006', 'nama' => 'Muhammad Naufal Firman Ghani', 'jurusan' => 'Teknik Mesin', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390004', 'nama' => 'Fadhil Tri Utama', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390005', 'nama' => 'Khamid Amaludin', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390006', 'nama' => 'Bagus Anugrah Ramadhan', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390008', 'nama' => 'Tri Yuli Yanto', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390002', 'nama' => 'Sulthan Annafi Wijoyo', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390012', 'nama' => 'Romadhon', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23390009', 'nama' => 'Muhammad Jidan', 'jurusan' => 'Teknik Otomotif', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490004', 'nama' => 'Zidni Maulana Abdillah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490001', 'nama' => 'Mohamad Khafidin', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490002', 'nama' => 'Saillan Nisa', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490003', 'nama' => 'Adnan Muzaki', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490005', 'nama' => 'Hasna Lutfiyah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490006', 'nama' => 'Azhar Saputra', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490007', 'nama' => 'Akhmad Alif Alghifari', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490008', 'nama' => 'Winarni Setianingsih', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '23490009', 'nama' => 'Fathi Khairi Adman', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '6', 'alamat' => '-'],
            ['nim' => '241100001', 'nama' => 'Muchammad Faizal Ikhsani', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100003', 'nama' => 'Farina Setya Rahesti', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100006', 'nama' => 'Ajeng Ayu Rosilah', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100007', 'nama' => 'Ivan Arsyadani', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100011', 'nama' => 'Yasmin Zahra Tushafa', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100012', 'nama' => 'Wawan Humadi', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100013', 'nama' => 'Safara Intan Berliana', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100014', 'nama' => 'Muhamad Adib', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100016', 'nama' => 'Friska Ayu Dwicahyani', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100017', 'nama' => 'M. Maulana Wahyono', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100018', 'nama' => 'Mahaputri Buana Devwitasari', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100020', 'nama' => 'Dwi Ulfatul Annisa', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100021', 'nama' => 'Wisnu Irsyad Pratama', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100023', 'nama' => 'Akhmad Nofal', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100024', 'nama' => 'Zahwa Aurellia Salsabila', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100025', 'nama' => 'Khoirur Roziqin', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100026', 'nama' => 'Ifa Nur Allyyani', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100030', 'nama' => 'Ananda Alfa Deka', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100031', 'nama' => 'Ilham Zenal Abidi', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100032', 'nama' => 'Dwi Ramadhani', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100033', 'nama' => 'Moh. Farkhan', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100034', 'nama' => 'Ichibang Akbar', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100035', 'nama' => 'Rani Lestarianto', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100036', 'nama' => 'Chelsea Cintia Muchty', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100038', 'nama' => 'Gina Puspita Widianto', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100042', 'nama' => 'Chaerul Wahyu Iman Syah', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100048', 'nama' => 'Muh. Hirzi Alfan Izzi', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '241100049', 'nama' => 'Mohammad Nur Fauzan ', 'jurusan' => 'Teknik Informatika', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100001', 'nama' => 'Isnaeni Nugroho', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100003', 'nama' => 'Muhammad Ilham Ahsanu Amala', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100007', 'nama' => 'Faqih Khoeru Rasyid', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100009', 'nama' => 'Faiz Zidane Nur Alam', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100010', 'nama' => 'Ichwan Rifqi Yulianto', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '242100011', 'nama' => 'Adib Ismail', 'jurusan' => 'Teknik Mesin', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '243100001', 'nama' => 'Firman Maulana', 'jurusan' => 'Teknik Otomotif', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '243100002', 'nama' => 'Faqih Armanda', 'jurusan' => 'Teknik Otomotif', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '243100003', 'nama' => 'Bagus Kurniawan', 'jurusan' => 'Teknik Otomotif', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '243100004', 'nama' => 'Dimas Setyo Nugroho', 'jurusan' => 'Teknik Otomotif', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '243100005', 'nama' => 'Adi Saputra', 'jurusan' => 'Teknik Otomotif', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100003', 'nama' => 'Raffa Khairullah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100004', 'nama' => 'Santi Ristiyanti', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100005', 'nama' => 'Raudhotul Nurul Farroh', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100006', 'nama' => 'Karunia Mukjizati Raffirna', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100007', 'nama' => 'Yasmin Mumtaz Aulia', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100008', 'nama' => 'M. Imtiyaz Pasha', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '244100009', 'nama' => 'Ummi Sari Rotul Jannah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '4', 'alamat' => '-'],
            ['nim' => '251110001', 'nama' => 'Sunandani Tonianingsih', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110002', 'nama' => 'Izzan Fauzi Azwan', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110003', 'nama' => 'M. Sekar De Rizki Akbar', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110004', 'nama' => 'Khilda Amelia', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110005', 'nama' => 'Dhini Aolia Rochmah', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110006', 'nama' => 'Zaqiah Ayu Anjani', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110007', 'nama' => 'Restu Yuni Saprina', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110008', 'nama' => 'Radith Jafar Pratama', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110009', 'nama' => 'Dea Setia', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110010', 'nama' => 'Semestha Abdu Fathi', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110011', 'nama' => 'Muhamad Maulana Yusuf', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110012', 'nama' => 'Adhi Prima Tantular', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110013', 'nama' => 'Hanif Muyassar', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110014', 'nama' => 'Andin Nia Ulfa', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110015', 'nama' => 'Ria Prihatin', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110016', 'nama' => 'Ranita Nurul Fitri', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110017', 'nama' => 'Nanda S. Dwi Andika Al Aziz', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110018', 'nama' => 'M. Adib Ikhsanal Mulaim', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110019', 'nama' => 'Salma Aulia', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110020', 'nama' => 'Ilmi Wildan Mukholadun', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110021', 'nama' => 'Fista Nadya Junita', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110022', 'nama' => 'Fatih Ananda Riadi', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110023', 'nama' => 'Bintang Ariyani', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110024', 'nama' => 'Yazid Abdullah', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110025', 'nama' => 'Muhammad Rizqi Adriansyah', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110026', 'nama' => 'Nabilah Putri Ade', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110027', 'nama' => 'Zelyka Pingki Azzahra', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110028', 'nama' => 'M. Zaldi Ghifari Akbar', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110029', 'nama' => 'Nayla Zahra Amalia', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110030', 'nama' => 'Widya Indah Lestari', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110031', 'nama' => 'Alif Guntur  Satriadi', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '251110041', 'nama' => 'Alinka Nailis Sa\'Adah', 'jurusan' => 'Teknik Informatika', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110001', 'nama' => 'Kayhan Dwi Andhika', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110002', 'nama' => 'Adittia Rido Prayogi', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110003', 'nama' => 'Faiz Zidane Nur Alam', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110004', 'nama' => 'Muhammad Amron Manzila', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110005', 'nama' => 'Afif Ikhwan Pratama', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110006', 'nama' => 'Moh. Farkhan Saputra', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110007', 'nama' => 'Irsyad Al Fauzi', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110008', 'nama' => 'Irgi Ahmad Fahrezi', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110009', 'nama' => 'Rifqi Mukti Zajuli', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110010', 'nama' => 'Bagus Bayu Samudro', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110011', 'nama' => 'Muhamad Khoerul Anam', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110012', 'nama' => 'Haikal Gibran Fadlal Haque', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110013', 'nama' => 'Mir\'Atu Zahro', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110014', 'nama' => 'Maulana Darmawan', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110015', 'nama' => 'Achmad Ulil Absor', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110016', 'nama' => 'Mukhammad Aldy Rochali', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110017', 'nama' => 'Abdullah Jafar Basalamah', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110018', 'nama' => 'Aulia Akbar Fitria Dinata', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110019', 'nama' => 'Ahmad Naufal Anas', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110020', 'nama' => 'Nur Lutfi Insani Raharjo', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110021', 'nama' => 'Khaerul Abijani', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '252110022', 'nama' => 'Danningsun Syaiku', 'jurusan' => 'Teknik Mesin', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110001', 'nama' => 'Farel Fatrizqi Alwan', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110002', 'nama' => 'Bagas Allaamsyah', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110003', 'nama' => 'Gillian Amul Husni', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110004', 'nama' => 'Mohammad Alfariski Saputra', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110005', 'nama' => 'Fredi Aji Laksono', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110007', 'nama' => 'Yosi Regi Pratama Bintang Fajar', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110008', 'nama' => 'Febriano Rizki Mulieya ', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110009', 'nama' => 'Muhammad Sahltum Rizqi Yanfaunnas', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110010', 'nama' => 'Muhamad Alifudin', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110011', 'nama' => 'Nasywa Kumara Bahtiar', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110012', 'nama' => 'Aziz Arya Saputra', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110013', 'nama' => 'Mario Arif Erlando Putra', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110014', 'nama' => 'Ahmad Nur Wahyudin', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '253110015', 'nama' => 'Sigit Andrianto', 'jurusan' => 'Teknik Otomotif', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110001', 'nama' => 'Intan Nurmiskiyah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110002', 'nama' => 'Nadya Zahratul Ramadhani', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110003', 'nama' => 'Abdul Rosyadi', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110004', 'nama' => 'Disto Rosdi Rafliyani', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110005', 'nama' => 'Arfan Mizan', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110006', 'nama' => 'Iffah Nazila Rahmah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110007', 'nama' => 'Fitriyani Syaqro', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110008', 'nama' => 'Putri Syakiroh', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110009', 'nama' => 'Annisa Putri', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110010', 'nama' => 'Athifah Nur Afiyah', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110011', 'nama' => 'Ali Rahman Kholis', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110012', 'nama' => 'Muhammad Rizqi Ni\'Am', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110013', 'nama' => 'Fatimah Tulzahra', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110014', 'nama' => 'Lintang Ayu Tiara', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110015', 'nama' => 'Rifqi Cahya Maulana Jamil', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110016', 'nama' => 'Rizal Fahmi Ghymnastiar', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
            ['nim' => '254110017', 'nama' => 'Muhammad Ma\'Riffatur Rizqi', 'jurusan' => 'Teknik Elektronika Industri', 'semester' => '2', 'alamat' => '-'],
        ];

        // Format ulang NIM dengan penambahan titik
        foreach ($dataMahasiswa as &$data) {
            $nim = $data['nim'];
            if (strlen($nim) === 8) {
                // Contoh: 23190008 -> 23.1.9.0008
                $data['nim'] = substr($nim, 0, 2) . '.' . substr($nim, 2, 1) . '.' . substr($nim, 3, 1) . '.' . substr($nim, 4);
            } elseif (strlen($nim) === 9) {
                // Contoh: 241100001 -> 24.1.10.0001
                $data['nim'] = substr($nim, 0, 2) . '.' . substr($nim, 2, 1) . '.' . substr($nim, 3, 2) . '.' . substr($nim, 5);
            }
        }
        unset($data); // Break reference

        // Looping untuk menjalankan formasi \App\Models\Mahasiswa::create() secara massal
        foreach ($dataMahasiswa as $data) {
            \App\Models\Mahasiswa::create($data);
        }

        // Variabel array dilepas dan memori yang tidak digunakan di-clear 
        // agar tidak menjadi sampah setelah proses database insertion/HTTP request selesai
        unset($dataMahasiswa);
        gc_collect_cycles();
    }
}