server {
    listen 80;
    server_name sistem-event.pbjt.web.id;

    location / {
        # 'sistem-event_app' adalah format penamaan otomatis service di Swarm (stackName_serviceName)
        # Port 8080 adalah port default internal dari image serversideup/php-fpm-nginx
        proxy_pass http://sistem-event_app:8080; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
